name = bacterial_mod
title = Evade & Shun:Bacterial
description = Adds an infection that players must survive, defend and fight  against!
depends = mobs, mobs_animal, forgotten_monsters
optional_depends = sfinv
min_minetest_version = 5.13
supported_games = minetest_game
unsupported_games = exile, extra_ordinance, pmb_core, mineclonia, mineclone2, nodecore